### PR TITLE
trying to fix image not displayed

### PR DESCRIPTION
**Pull request by Sakurann**

### CODE REVIEW

**Comment by jischr** [comment]
Ok got this to work: PNG is fine (don't need SVG). Update image reference like below.
```
![WorkplaceCredential Storyboard](./spec/assets/workplacecredential_storyboard.png)
```

I do see reference to having it in a www folder. i'm not sure if thats required or just the repos preference. we may have to deploy to see if it works.
https://github.com/decentralized-identity/sidetree/blob/master/docs/core.md?plain=1#L7

**Comment by Sakurann** [comment]
Thank you, Jen! Updated - should be ready to merge!

**Comment by jischr** [comment]
@Sakurann should be able to remove the svg file but other than that, looks good!

**Comment by Sakurann** [comment]
done

**Review by jischr — APPROVED** [review]

**Pull request merged**
