### PR TITLE
Handling of relative kid for v1.0 of the profile

### PR DESCRIPTION
**Pull request by troyronda**
Part of #44

### CODE REVIEW

**Comment by Sakurann** [comment]
I think we need to wait for a resolution on https://github.com/w3c/vc-data-model/issues/914 before we merge this PR

**Review by Sakurann — CHANGES_REQUESTED** [review]
I think it should either be either of: 
1. adding the clarification that the DID in the absolute DID URL MUST match DID in the `iss` 
2. in is only relative DID URL

Keeping both will lead to confusion. 
It is true that option 1 has been recommended usually. and while recently there are more discussions on the benefit of option2, we do not have an industry conensus yet. while we don't have it, i am not comfortable with adding it. and suggest we start with option 1 while keeping an issue open to move towards option2.

**Review by quartzjer — APPROVED** [review]

**Comment by Sakurann** [comment]
Could we please add more text on safer way for absolute url processing.
and to add text wrt security context behind the text

**Comment by tplooker** [comment]
The security issue with allowing absolute url's in the kid field is that an implementation can easily forget to check the did portion of the kid field to the iss value by just verifying the JWT based on the kid field. Failing to do that leads to the verifier to believe the JWT was signed by an issuer it was not. By using a relative URL in the kid field, the verifier has to use both the iss and kid values to resolve the public key required to validate the JWT therefore removing the possibility of the scenario described above.

**Comment by jischr** [comment]
@troyronda can you separate this out for the v0.1 release that we discussed last week?

**Comment by troyronda** [comment]
@jischr @Sakurann @tplooker I created a note describing the current situation.
#77

Summary:
- Noted that implementors currently use an absolute `kid` URI in VCs.
- Guidance on absolute and relative URIs.
- Noted the current debate and the potential for requirement changes from the spec/profile.
- Due to the potential for transition, implementors may want to consider accepting both.

**Review by Sakurann — APPROVED** [review]

**Pull request closed without merging**
