### PR TITLE
specify revocation version add v0.1.0 spec

### PR DESCRIPTION
**Pull request by dtmcg**
address issue 67 https://github.com/decentralized-identity/jwt-vc-presentation-profile/issues/67

### CODE REVIEW

**Comment by jischr** [comment]
@dtmcg i think we should delete spec/ and just keep everything in one folder for now until we officially fork. it will get too confusing to try to maintain two versions.

**Review by Sakurann — APPROVED** [review]
I agree with spec.md changes. The rest will leave to @dtmcg to figure out when publishing v0.1 and trust no normaive changes are made in the examples :)

**Review by Sakurann — CHANGES_REQUESTED** [review]
I want to re-read current text before signing off to v0.1.0

**Comment by Sakurann** [comment]
@dtmcg  can we please break this PR into two - revocation spec version (which has issues per #19 ) and v0.0.1 of a whole spec?

**Pull request closed without merging**
