### PR TITLE
Add jwk DIDs

### PR DESCRIPTION
**Pull request by nklomp**
This PR adds did:jwk support, aligning this profile more with the upcoming Dutch Decentralized Identity Profile (no link yet).
Adding did:jwk has been discussed in #80 and last meeting.
I think the main outstanding questions is, whether did:jwk support should be mandatory or optional (did:web and ion are mandatory, so I added jwk as mandatory as well)

Also has some small editorial changes like spelling errors, and adding myself as contributor

### CODE REVIEW

**Comment by jischr** [comment]
@quartzjer Are there plans to "freeze" the version of `did:jwk` so we can reference it in the profile?

**Comment by jischr** [comment]
Waiting for v1.0 to merge this

**Comment by quartzjer** [comment]
> @quartzjer Are there plans to "freeze" the version of `did:jwk` so we can reference it in the profile?

Good idea, I created a v1.0 release of `did:jwk` so serve as the official stable reference: https://github.com/quartzjer/did-jwk/tree/v1.0

**Review by quartzjer — APPROVED** [review]

**Review by Sakurann — APPROVED** [review]
given this is for v1 and is merged after we cut v0.01

**Comment by jischr** [comment]
Yep, thats why this was moved back to draft and with milestone.

**Comment by Sakurann** [comment]
@nklomp we have v.0.0.1 now, so please mark this ready for review and merge :)

**Comment by nklomp** [comment]
Marked as ready. I do not have permissions to merge

**Review by brentzundel — APPROVED** [review]

**Review by dwaite — APPROVED** [review]

**Pull request merged**
